config/routes.rb
Rails.application.routes.draw do
  root 'pages#index'

  namespace :admin do
    get '/', to: 'pages#index'

    resources :users
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  include Clearance::User

  validates :first_name, presence: true
  validates :last_name, presence: true
end

app/controllers/admin/application_controller.rb
module Admin
  class ApplicationController < ActionController::Base
    include Clearance::Controller
    # Prevent CSRF attacks by raising an exception.
    # For APIs, you may want to use :null_session instead.
    protect_from_forgery with: :exception

    layout 'admin'

    before_action :require_login
  end
end

app/controllers/admin/pages_controller.rb
module Admin
  class PagesController < Admin::ApplicationController
    def index
    end
  end
end

app/controllers/admin/users_controller.rb
module Admin
  class UsersController < Admin::ApplicationController
    before_action :set_user, only: [:show, :edit, :update, :destroy]

    def index
      @users = User.all
      render :index, locals: { users: @users }
    end

    def show
      render :show, locals: { user: @user }
    end

    def new
      @user = User.new
      render :new, locals: { user: @user }
    end

    def edit
      render :edit, locals: { user: @user }
    end

    def create
      @user = User.new(user_params)

      if @user.save
        redirect_to admin_users_url, notice: 'User was successfully created.'
      else
        render :new, locals: { user: @user }
      end
    end

    def update
      if @user.update(user_params)
        redirect_to admin_users_url, notice: 'User was successfully updated.'
      else
        render :edit, locals: { user: @user }
      end
    end

    def destroy
      @user.destroy
      redirect_to admin_users_url, notice: 'User was successfully destroyed.'
    end

    private

    def set_user
      @user = User.find(params[:id])
    end

    def user_params
      params.require(:user).permit(:first_name, :last_name, :email, :password, :admin)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Clearance::Controller
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/pages/index.html.slim
| Admin home

app/views/admin/users/_form.html.slim
= simple_form_for([:admin, user]) do |f|
  = f.error_notification

  .form-inputs
    = f.input :first_name
    = f.input :last_name
    = f.input :email
    = f.input :password
    = f.input :admin

  .form-actions
    = f.button :submit

app/views/admin/users/edit.html.slim
h1 Editing user

== render 'form', user: user

= link_to 'Show', admin_user_path(user)
'|
= link_to 'Back', admin_users_path

app/views/admin/users/index.html.slim
h1 Listing users

table
  thead
    tr
      th Firstname
      th Lastname
      th Email
      th Password
      th Admin?
      th
      th
      th

  tbody
    - users.each do |user|
      tr
        td = user.first_name
        td = user.last_name
        td = user.email
        td = user.password
        td = user.admin
        td = link_to 'Show', admin_user_path(user)
        td = link_to 'Edit', edit_admin_user_path(user)
        td = link_to 'Destroy', admin_user_path(user), data: { confirm: 'Are you sure?' }, method: :delete

br

= link_to 'New User', new_admin_user_path

app/views/admin/users/new.html.slim
h1 New user

== render 'form', user: user

= link_to 'Back', admin_users_path

app/views/admin/users/show.html.slim
p#notice = notice

p
  strong Firstname:
  = user.first_name
p
  strong Lastname:
  = user.last_name
p
  strong Email:
  = user.email
p
  strong Password:
  = user.password

p
  strong Admin?:
  = user.admin

= link_to 'Edit', edit_admin_user_path(user)
'|
= link_to 'Back', admin_users_path

app/views/layouts/_flash_messages.html.slim
- flash.each do |key, value|
  div class="flash #{ key }"
    = value

app/views/layouts/admin.html.slim
doctype html
html
  head
    title Demo
    = stylesheet_link_tag    'admin', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'admin', 'data-turbolinks-track' => true
    = csrf_meta_tags

  body
    - if signed_in?
      | Signed in as: #{ current_user.email }
      = button_to 'Sign out', sign_out_path, method: :delete
    - else
      = link_to 'Sign in', sign_in_path

    #flash
      = render 'layouts/flash_messages', flash: flash

    = yield

app/views/layouts/application.html.slim
doctype html
html
  head
    title Demo
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags

  body
    - if signed_in?
      | Signed in as: #{ current_user.email }
      = button_to 'Sign out', sign_out_path, method: :delete
    - else
      = link_to 'Sign in', sign_in_path

    #flash
      = render 'layouts/flash_messages', flash: flash

    = yield

app/views/pages/index.html.slim
| Welcome to the demo site.